### ISSUE TITLE
Extract colors to a variable

### ISSUE THREAD

**Issue by martijnjanssen** [WISVCH/symposium#35]
Colors should not be scattered all over the place. They should be declared at a central place.

**Comment by TimvdLippe** [comment]
Should be placed inside `app-theme.html` in the root folder (imported in `index.html`) where all variables are declared inside `html {}`

**Comment by TimvdLippe** [comment]
CSS variables are not supported in every browser, so let's keep it like this for now. We can revisit next year :smile:
