### ISSUE TITLE
Check that website works in other browsers

### ISSUE THREAD

**Issue by TimvdLippe** [WISVCH/symposium#63]
We have to check this, but I also found out we are using `const` instead of `var`: https://github.com/WISVCH/symposium/blob/master/index.html#L269-L273

**Comment by martijnjanssen** [comment]
And we should use `var` instead of `const` due to the fact that we are not using ES6 yet, right? Every `const` should be replaced by a `var`.

**Comment by TimvdLippe** [comment]
Yes :)

**Comment by martijnjanssen** [comment]
It also appears that a lot of content does not render/show in safari:
- Iron icons are not loaded
- WISVCH-footer is not loaded
- Program tab is not working and just switches to the homepage

**Comment by martijnjanssen** [comment]
I believe this will be partially fixed in #58
