### ISSUE TITLE
All issues that need to be fixed before 07-03

### ISSUE THREAD

**Issue by dvantetering** [WISVCH/symposium#73]
- [x] #66 ~Checkbox for invoice~ Add a comment for the invoice
- [x] #68 Change payment URLs
- [x] #70 Add sponsors
- [x] #72 Speaker Layout
- [x] #71 Change program

**Comment by TimvdLippe** [comment]
Speakers are ready in #90, which are almost ready to be merged :smile:

**Comment by TimvdLippe** [comment]
All fixed :tada:
