### ISSUE TITLE
Enable serving with http/2

### ISSUE THREAD

**Issue by martijnjanssen** [WISVCH/symposium#92]
This should be ~fairly easy~ with the config.

**Comment by praseodym** [comment]
No use, our reverse proxy doesn't do HTTP/2.

**Comment by martijnjanssen** [comment]
This was not an issue that needed fixing right away, this was something more long-term to think about. We don't want to be stuck without HTTP/2 forever.

**Comment by praseodym** [comment]
You weren't implying that by saying it would be "fairly easy".

**Comment by martijnjanssen** [comment]
Enabling for the container (this project only) would be fairly easy. Integrating it into the entire server architecture is something else entirely :)

**Comment by TimvdLippe** [comment]
https://symposium.ch.tudelft.nl/2017/ is now using H2 :tada: 

![image](https://cloud.githubusercontent.com/assets/5948271/25066963/62fcdf58-2235-11e7-944c-655a39be7ea1.png)

**Comment by martijnjanssen** [comment]
While this is true, the container does not use HTTP/2 right now, we will have to enable this in the `nginx.conf`.

**Comment by praseodym** [comment]
Doesn't matter: https://trac.nginx.org/nginx/ticket/923

**Comment by TimvdLippe** [comment]
@praseodym Could you elaborate? I am not familiar with the nginx proxy config. Does the linked ticket mean that it is already working or that something we require will not work?

**Comment by praseodym** [comment]
nginx doesn't (and in the foreseeable future won't) have support for using HTTP/2 to an upstream server when acting as a reverse proxy. Since the Symposium container will always be used behind a reverse proxy, it doesn't matter whether it supports HTTP/2 since that will never be used.
