### ISSUE TITLE
Ngi-NGN renamed to KNVI

### ISSUE THREAD

**Issue by bvanderdrift** [WISVCH/symposium#95]
- [ ] Replace logo @ partners - http://static1.squarespace.com/static/5148b4d0e4b0b0be2ded2ab1/t/514e22ede4b0123f55d1d097/1490111175764/
- [ ] Rename 'Ngi-NGN member' ticket title to 'KNVI member'

**Comment by TimvdLippe** [comment]
@bvanderdrift what is the URL we need to link to?

**Comment by TimvdLippe** [comment]
Firebase rules have been updated accordingly. We still accept NGI-NGN member for now, until we flip on the live website.
